name = "mistweaver"
version = "1.0.0"
description = "A Phoenix-inspired web framework for Gleam, built on Mist and Lustre."
licences = ["Apache-2.0"]
repository = { type = "github", user = "bradcypert", repo = "mistweaver" }
links = [{ title = "Docs", href = "https://bradcypert.github.io/mistweaver/" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
mist = ">= 6.0.3 and < 7.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gloo = ">= 1.0.2 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
birl = ">= 2.0.0 and < 3.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
logging = ">= 1.5.0 and < 2.0.0"
lustre = ">= 5.7.0 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
